# Generated by Django 4.2 on 2023-04-12 09:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import smssender.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('cn', 'CN'), ('rn', 'RN')], max_length=10)),
                ('criteria', models.CharField(choices=[('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('an', 'Andijan'), ('bh', 'Bukhara'), ('dz', 'Djizzakh'), ('fr', 'Fergana'), ('sr', 'Sirdarya'), ('ks', 'Kashkadarya'), ('nm', 'Namangan'), ('nv', 'Navoi'), ('kr', 'Karakalpakstan'), ('sm', 'Samarkand'), ('ts', 'Tashkent'), ('su', 'Surkhandarya'), ('kh', 'Khorezm')], max_length=20)),
                ('notification', models.CharField(choices=[('cn', 'CN'), ('rn', 'RN')], max_length=30)),
                ('tel_number', models.CharField(max_length=12, validators=[smssender.models.only_int])),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_addr', models.CharField(choices=[('ncc-rn', 'NCC-RN'), ('ncc-cn', 'NCC-CN')], max_length=10)),
                ('sms_text', models.CharField()),
                ('tel_number_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12, validators=[smssender.models.only_int]), size=None)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
