# Generated by Django 4.2 on 2023-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BSC/RNC', 'BSC/RNC'), ('BTS', 'BTS'), ('CORE', 'CORE')], max_length=30)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('ПР', 'ПР')], max_length=30)),
                ('category', models.CharField(choices=[('Тех проблема', 'Тех проблема'), ('ЭС и Клим', 'ЭС и Клим'), ('ПР', 'ПР'), ('Выясняется', 'Выясняется')], max_length=30)),
                ('responsible_area', models.CharField(choices=[('Другие ЗО', 'Другие ЗО'), ('Эксплуатация', 'Эксплуатация'), ('Выясняется', 'Выясняется')], max_length=30)),
                ('category_for_hub', models.CharField(choices=[('AC/DC breaker', 'AC/DC breaker'), ('Bad RX level', 'Bad RX level'), ('High Temp', 'High Temp'), ('Incorrect work', 'Incorrect work'), ('Leased Line', 'Leased Line'), ('Low voltage', 'Low voltage'), ('Power', 'Power'), ('TI_DNO', 'TI_DNO'), ('TI_ESO', 'TI_ESO'), ('TI_MW', 'TI_MW'), ('TI_SAQ', 'TI_SAQ'), ('TI_SDH', 'TI_SDH'), ('Unplanned work', 'Unplanned work'), ('WB', 'WB'), ('Выясняется', 'Выясняется')], max_length=30)),
                ('category_for_core', models.CharField(choices=[('Core', 'Core'), ('GPRS', 'GPRS'), ('Roaming', 'Roaming'), ('MPLS', 'MPLS'), ('Power', 'Power'), ('High Temp', 'High Temp')], max_length=30)),
                ('hub_site', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('fg_avb', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('mw_link', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('mw_equipment', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('mw_vendor', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('bts_vendor', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('power_off_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('sector_block_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('low_battery_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('dg_start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('battery_life_time', models.TimeField(blank=True, default=None, null=True)),
                ('chronic_site', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('chronic_hours', models.IntegerField(blank=True, default=None, null=True)),
                ('problem', models.CharField()),
                ('reason', models.CharField()),
                ('influence', models.CharField()),
                ('effect', models.CharField(choices=[('С влиянием', 'С влиянием'), ('Без влияния', 'Без влияния')], max_length=30)),
                ('informed', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('duration', models.DurationField(blank=True, default=None, null=True)),
                ('effect_level', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('description', models.CharField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('year_week', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'verbose_name': 'SMS log', 'verbose_name_plural': 'SMS logs'},
        ),
        migrations.AlterModelOptions(
            name='smsreceiver',
            options={'verbose_name': 'SMS receiver', 'verbose_name_plural': 'SMS receivers'},
        ),
        migrations.AlterField(
            model_name='smsreceiver',
            name='notification',
            field=models.CharField(choices=[('internet', 'Internet Incidents'), ('roaming', 'Roaming Incidents'), ('core', 'Core Incidents'), ('power', 'Power Incidents'), ('controller', 'BSC/RNC Incidents'), ('chronic', 'Chronic-Down Sites'), ('hub', 'HUB Sites Incidents'), ('report', 'Report Message')], max_length=30),
        ),
    ]
