# Generated by Django 4.2.2 on 2023-06-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smssender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmreport',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='type',
            field=models.CharField(choices=[('BSC/RNC', 'BSC/RNC'), ('HUB', 'HUB'), ('CHRONIC', 'CHRONIC'), ('CORE', 'CORE')], max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smsreceiver',
            name='criteria',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('Andijan', 'Andijan'), ('Bukhara', 'Bukhara'), ('Djizzakh', 'Djizzakh'), ('Fergana', 'Fergana'), ('Sirdarya', 'Sirdarya'), ('Kashkadarya', 'Kashkadarya'), ('Namangan', 'Namangan'), ('Navoi', 'Navoi'), ('Karakalpakstan', 'Karakalpakstan'), ('Samarkand', 'Samarkand'), ('Tashkent', 'Tashkent'), ('Surkhandarya', 'Surkhandarya'), ('Khorezm', 'Khorezm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smsreceiver',
            name='network',
            field=models.CharField(choices=[('CN', 'CN'), ('RN', 'RN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='smsreceiver',
            name='notification',
            field=models.CharField(choices=[('Internet', 'Internet Incidents'), ('Roaming', 'Roaming Incidents'), ('Core', 'Core Incidents'), ('Power/HighTemp', 'Power/HighTemp Incidents'), ('BSC/RNC', 'BSC/RNC Incidents'), ('Chronic', 'Chronic-Down Sites'), ('Hub', 'HUB Sites Incidents'), ('Report', 'Report Message')], max_length=30),
        ),
    ]
