# Generated by Django 4.2 on 2023-07-04 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smssender', '0002_alter_alarmreport_is_complete_alter_alarmreport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smsreceiver',
            name='notification',
            field=models.CharField(choices=[('GPRS', 'GPRS Incidents'), ('Roaming', 'Roaming Incidents'), ('Core', 'Core Incidents'), ('Power/HighTemp', 'Power/HighTemp Incidents'), ('BSC/RNC', 'BSC/RNC Incidents'), ('Chronic', 'Chronic-Down Sites'), ('Hub', 'HUB Sites Incidents'), ('Report', 'Report Message')], max_length=30),
        ),
    ]
