# Generated by Django 4.2 on 2023-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssender', '0002_alarmreport_alter_smslog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmreport',
            name='effect_level',
        ),
        migrations.RemoveField(
            model_name='alarmreport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='alarmreport',
            name='week',
        ),
        migrations.RemoveField(
            model_name='alarmreport',
            name='year',
        ),
        migrations.RemoveField(
            model_name='alarmreport',
            name='year_week',
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='category_for_core',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('GPRS', 'GPRS'), ('Roaming', 'Roaming'), ('MPLS', 'MPLS'), ('Power', 'Power'), ('High Temp', 'High Temp')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='category_for_hub',
            field=models.CharField(blank=True, choices=[('AC/DC breaker', 'AC/DC breaker'), ('Bad RX level', 'Bad RX level'), ('High Temp', 'High Temp'), ('Incorrect work', 'Incorrect work'), ('Leased Line', 'Leased Line'), ('Low voltage', 'Low voltage'), ('Power', 'Power'), ('TI_DNO', 'TI_DNO'), ('TI_ESO', 'TI_ESO'), ('TI_MW', 'TI_MW'), ('TI_SAQ', 'TI_SAQ'), ('TI_SDH', 'TI_SDH'), ('Unplanned work', 'Unplanned work'), ('WB', 'WB'), ('Выясняется', 'Выясняется')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='description',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
