# Generated by Django 4.2 on 2023-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssender', '0004_alter_alarmreport_influence'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmreport',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='battery_life_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Battery life time'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='bts_vendor',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='BTS вендор'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='category',
            field=models.CharField(choices=[('Тех проблема', 'Тех проблема'), ('ЭС и Клим', 'ЭС и Клим'), ('ПР', 'ПР'), ('Выясняется', 'Выясняется')], max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='category_for_core',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('GPRS', 'GPRS'), ('Roaming', 'Roaming'), ('MPLS', 'MPLS'), ('Power', 'Power'), ('High Temp', 'High Temp')], default=None, max_length=30, null=True, verbose_name='Категория для Core'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='category_for_hub',
            field=models.CharField(blank=True, choices=[('AC/DC breaker', 'AC/DC breaker'), ('Bad RX level', 'Bad RX level'), ('High Temp', 'High Temp'), ('Incorrect work', 'Incorrect work'), ('Leased Line', 'Leased Line'), ('Low voltage', 'Low voltage'), ('Power', 'Power'), ('TI_DNO', 'TI_DNO'), ('TI_ESO', 'TI_ESO'), ('TI_MW', 'TI_MW'), ('TI_SAQ', 'TI_SAQ'), ('TI_SDH', 'TI_SDH'), ('Unplanned work', 'Unplanned work'), ('WB', 'WB'), ('Выясняется', 'Выясняется')], default=None, max_length=30, null=True, verbose_name='Категория для БС'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='chronic_hours',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Хроник часы'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='chronic_site',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Хроник сайт'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан в'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='description',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='dg_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время начала DG'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='effect',
            field=models.CharField(choices=[('С влиянием', 'С влиянием'), ('Без влияния', 'Без влияния')], max_length=30, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='fg_avb',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='Наличие FG'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='hub_site',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Хаб сайт'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='influence',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Влияние'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='informed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Информирован'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('ПР', 'ПР')], max_length=30, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='low_battery_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время низкого заряда батареи'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='mw_equipment',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='МW оборудование'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='mw_link',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='MW линк'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='mw_vendor',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='MW вендор'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='power_off_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время отключения питания'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='problem',
            field=models.CharField(verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='reason',
            field=models.CharField(verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='region',
            field=models.CharField(max_length=30, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='responsible_area',
            field=models.CharField(choices=[('Другие ЗО', 'Другие ЗО'), ('Эксплуатация', 'Эксплуатация'), ('Выясняется', 'Выясняется')], max_length=30, verbose_name='Зона ответственности'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='sector_block_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время блока сектора'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='start_time',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='type',
            field=models.CharField(choices=[('BSC/RNC', 'BSC/RNC'), ('BTS', 'BTS'), ('CORE', 'CORE')], max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='alarmreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено в'),
        ),
    ]
